name: Frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  http: ^1.3.0
  kakao_flutter_sdk_user: ^1.1.1
  flutter_dotenv: ^5.2.1
  flutter_colorful_tab: ^0.1.1
  firebase_messaging: ^15.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  network_info_plus: ^4.0.1
  firebase_messaging: ^15.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/kakaotalk_icon.png
    - assets/images/alert.png
    - assets/images/setting.png
    - assets/images/refrigerator.png
    - assets/images/menu.png
    - assets/images/recipe.png
    - assets/images/favorits.png
    - assets/images/cart.png
    - assets/images/plus.png
    - assets/images/levelplus.png
    - assets/images/minus.png
    - assets/refrigerators/R1.png
    - assets/refrigerators/R2.png
    - assets/refrigerators/R3.png
    - assets/hearts/blankheart.png
    - assets/hearts/filledheart.png
    - .env