# Generated by Django 5.2 on 2025-05-10 07:46

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('duration', models.DurationField(default=datetime.timedelta(days=7))),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('fridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_count', models.IntegerField(help_text='냉장고 단 수')),
                ('model_label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('recipe_image', models.CharField(max_length=255)),
                ('category1', models.CharField(max_length=100)),
                ('category2', models.CharField(max_length=100)),
                ('category3', models.CharField(max_length=100)),
                ('category4', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('steps', models.TextField(help_text='요리 순서(내용)')),
                ('serving_size', models.CharField(help_text='N인분', max_length=50)),
                ('cooking_time', models.CharField(help_text='~분 이내', max_length=50)),
                ('cooking_level', models.CharField(choices=[('anyone', '아무나'), ('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='anyone', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_id', models.CharField(max_length=255, unique=True)),
                ('social_provider', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FridgeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.IntegerField(help_text='냉장고 내의 재료의 위치(단수)', validators=[django.core.validators.MinValueValidator(0)])),
                ('storable_due', models.DateTimeField(null=True)),
                ('ingredient_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.category')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.fridge')),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.savedrecipes')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.recipes')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.savedrecipeingredients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
