# Generated by Django 5.2 on 2025-05-30 06:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStorageLife',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('storage_life', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('fridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_count', models.IntegerField(help_text='냉장고 단 수')),
                ('model_label', models.CharField(default='기본 냉장고', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'xndApp_fridge',
                'ordering': ['user', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('recipe_image', models.CharField(max_length=255)),
                ('category1', models.CharField(max_length=100)),
                ('category2', models.CharField(max_length=100)),
                ('category3', models.CharField(max_length=100)),
                ('category4', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('ingredient_all', models.TextField(max_length=300)),
                ('steps', models.TextField(help_text='요리 순서(내용)')),
                ('serving_size', models.CharField(help_text='N인분', max_length=50)),
                ('cooking_time', models.CharField(help_text='~분 이내', max_length=50)),
                ('cooking_level', models.CharField(choices=[('anyone', '아무나'), ('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='anyone', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_id', models.CharField(max_length=255, unique=True)),
                ('social_provider', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FridgeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.IntegerField(help_text='냉장고 내의 재료의 위치(단수)', validators=[django.core.validators.MinValueValidator(0)])),
                ('storable_due', models.DateTimeField(null=True)),
                ('ingredient_pic', models.CharField(max_length=255)),
                ('foodStorageLife', models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='XndApp.foodstoragelife')),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.fridge')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient')),
            ],
            options={
                'db_table': 'xndapp_fridgeingredients',
                'ordering': ['-storable_due'],
            },
        ),
        migrations.CreateModel(
            name='SavedRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savedRecipes',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='SavedRecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.savedrecipes')),
            ],
            options={
                'db_table': 'savedRecipeIngredients',
                'ordering': ['recipe'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50)),
                ('recipe', models.ManyToManyField(related_name='tags', to='XndApp.recipes')),
            ],
        ),
        migrations.AddField(
            model_name='fridge',
            name='user',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.recipes')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '전송 예정'), ('sent', '전송 성공'), ('failed', '전송 실패'), ('cancelled', '전송 취소')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fridge_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XndApp.fridgeingredients')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='XndApp_push_user_id_1a16ed_idx'), models.Index(fields=['user', 'is_read'], name='XndApp_push_user_id_f5b341_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(max_length=500)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='XndApp_devi_user_id_fc72d0_idx')],
                'unique_together': {('user', 'fcm_token')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ingredient')},
            },
        ),
    ]
