# Generated by Django 5.2 on 2025-05-01 17:44

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('social_id', models.CharField(max_length=255, unique=True)),
                ('social_provider', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=10)),
                ('email', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
    ]
