# Generated by Django 5.2 on 2025-05-23 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStorageLife',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('storage_life', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='savedrecipeingredients',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fridgeingredients',
            name='category',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredient_all',
            field=models.TextField(default=100, max_length=300),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='tags',
            name='recipe',
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='foodStorageLife',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='XndApp.foodstoragelife'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'ingredient')},
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.recipes')),
            ],
            options={
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='tags',
            name='recipe',
            field=models.ManyToManyField(related_name='tags', to='XndApp.recipes'),
        ),
    ]
