# Generated by Django 5.2 on 2025-09-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeingredients',
            name='status',
            field=models.CharField(choices=[('inbound', '입고'), ('outbound', '출고'), ('in_use', '사용중')], default='inbound', help_text='식재료 상태 (입고/출고/사용중)', max_length=20),
        ),
    ]
