# Generated by Django 5.2 on 2025-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredients',
            name='ingredient',
            field=models.CharField(max_length=255),
        ),
    ]
