# Generated by Django 5.2.1 on 2025-05-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XndApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tags",
            name="recipe",
        ),
        migrations.AddField(
            model_name="tags",
            name="recipe",
            field=models.ManyToManyField(related_name="tags", to="XndApp.recipes"),
        ),
    ]
