# Generated by Django 5.2 on 2025-05-30 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0002_alter_fridgeingredients_ingredient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fridgeingredients',
            table='fridgeingredients',
        ),
    ]
