# Generated by Django 5.2.1 on 2025-05-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XndApp", "0002_foodstoragelife_ingredient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fridgeingredients",
            name="ingredient_pic",
            field=models.CharField(default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
