# Generated by Django 5.2 on 2025-05-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0002_remove_tags_recipe_tags_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='ingredient',
            field=models.TextField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
