# Generated by Django 4.2.8 on 2025-10-09 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0002_fridgeingredients_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeingredients',
            name='category_yolo',
            field=models.CharField(default='FALLBACK_MODE', help_text='YOLO 객체 탐지 카테고리', max_length=100),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='date_recognition_confidence',
            field=models.FloatField(default=0.0, help_text='유통기한 OCR 인식 신뢰도'),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='date_type_confidence',
            field=models.FloatField(default=0.0, help_text='유통기한 유형 신뢰도'),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='파이프라인이 인식한 유통기한 날짜', null=True),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='expiry_date_status',
            field=models.CharField(default='NOT_FOUND', help_text='유통기한 상태 (CONFIRMED, UNCERTAIN, EXPIRED 등)', max_length=15),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='product_name_ocr',
            field=models.CharField(blank=True, help_text='OCR Word2Vec 추출 식재료명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='product_similarity_score',
            field=models.FloatField(default=0.0, help_text="Word2Vec '식재료' 앵커 워드 유사도 점수 (0.0~1.0)"),
        ),
        migrations.AddField(
            model_name='fridgeingredients',
            name='yolo_confidence',
            field=models.FloatField(default=0.0, help_text='YOLO 객체 인식 신뢰도 점수 (0.0~1.0)'),
        ),
        migrations.AlterField(
            model_name='fridgeingredients',
            name='foodStorageLife',
            field=models.ForeignKey(default=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='XndApp.foodstoragelife'),
        ),
    ]
