# Generated by Django 5.2 on 2025-05-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0002_foodstoragelife_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fridgeingredients',
            options={'ordering': ['-storable_due']},
        ),
        migrations.AlterModelTable(
            name='fridgeingredients',
            table='xndapp_fridgeingredients',
        ),
    ]
