# Generated by Django 4.2.8 on 2025-10-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0003_fridgeingredients_category_yolo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='XndApp.tags'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
