# Generated by Django 5.2.1 on 2025-05-23 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XndApp", "0003_fridgeingredients_ingredient_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fridge",
            name="user",
            field=models.ForeignKey(
                default=111,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
