# Generated by Django 5.2 on 2025-05-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0003_recipes_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='ingredient',
            new_name='ingredient_all',
        ),
    ]
