# Generated by Django 5.2 on 2025-05-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0003_alter_fridgeingredients_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient'),
        ),
    ]
