# Generated by Django 5.2 on 2025-05-31 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0004_alter_fridgeingredients_ingredient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fridgeingredients',
            table='xndapp_fridgeingredients',
        ),
    ]
