# Generated by Django 4.2.8 on 2025-10-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0004_remove_tags_recipe_recipes_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeingredients',
            name='storage_location',
            field=models.CharField(choices=[('fridge', '냉장실'), ('freezer', '냉동실'), ('external', '외부')], default='fridge', help_text='보관 위치 (냉장실/냉동실/외부)', max_length=20),
        ),
    ]
