# Generated by Django 5.2 on 2025-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0004_rename_ingredient_recipes_ingredient_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStorageLife',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('storage_life', models.SmallIntegerField()),
            ],
        ),
    ]
