# Generated by Django 5.2 on 2025-05-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0004_alter_fridge_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='ingredient_all',
            new_name='ingredient_name',
        ),
    ]
