# Generated by Django 5.2 on 2025-05-28 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0004_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('schedule_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '전송 예정'), ('sent', '전송 성공'), ('failed', '전송 실패'), ('cancelled', '전송 취소')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'is_active'], name='XndApp_devi_user_id_fc72d0_idx'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='fridge_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XndApp.fridgeingredients'),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['user', 'status'], name='XndApp_push_user_id_1a16ed_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['user', 'is_read'], name='XndApp_push_user_id_f5b341_idx'),
        ),
    ]
