# Generated by Django 5.2.1 on 2025-06-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XndApp", "0005_alter_fridgeingredients_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fridgeingredients",
            name="ingredient",
        ),
        migrations.AddField(
            model_name="fridgeingredients",
            name="ingredient_name",
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
