# Generated by Django 4.2.8 on 2025-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0005_fridgeingredients_storage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredients',
            name='ingredient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fridgeingredients',
            name='yolo_confidence',
            field=models.FloatField(default=0.0, help_text='YOLO 객체 인식 신뢰도 점수 (0.0~1.0)', null=True),
        ),
    ]
