# Generated by Django 5.2 on 2025-05-28 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0005_rename_ingredient_all_recipes_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='ingredient_name',
            new_name='ingredient_all',
        ),
    ]
