# Generated by Django 4.2.8 on 2025-10-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0006_alter_fridgeingredients_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridgeingredients',
            name='memo',
            field=models.TextField(blank=True, help_text='식재료에 대한 메모', max_length=200, null=True),
        ),
    ]
