# Generated by Django 5.2 on 2025-05-19 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0007_ingredient_cart_amount_cart_new_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='new_ingredient',
        ),
        migrations.AlterField(
            model_name='cart',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XndApp.ingredient'),
        ),
    ]
