# Generated by Django 4.2.8 on 2025-10-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0007_fridgeingredients_memo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='XndApp.recipes'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'ingredient', 'recipe')},
        ),
    ]
