# Generated by Django 4.2.8 on 2025-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0008_alter_cart_unique_together_cart_recipe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
