# Generated by Django 5.2 on 2025-05-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0008_alter_cart_options_remove_cart_new_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
