# Generated by Django 4.2.8 on 2025-10-30 11:20

from django.db import migrations, models


def migrate_budget_data(apps, schema_editor):
    """기존 budget 데이터를 monthly_budget로 이전"""
    User = apps.get_model('XndApp', 'User')
    for user in User.objects.all():
        # 기존 budget 값을 monthly_budget으로 설정
        # monthly_spent는 0으로 시작 (새로운 달로 간주)
        if user.budget and user.budget > 0:
            user.monthly_budget = user.budget
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0009_user_budget'),
    ]

    operations = [
        # 1. 새로운 필드들 추가
        migrations.AddField(
            model_name='user',
            name='budget_reset_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='last_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_budget',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_spent',
            field=models.IntegerField(default=0),
        ),
        # 2. 기존 budget 데이터를 monthly_budget로 이전
        migrations.RunPython(migrate_budget_data, reverse_code=migrations.RunPython.noop),
        # 3. 기존 budget 필드 제거
        migrations.RemoveField(
            model_name='user',
            name='budget',
        ),
    ]
