# Generated by Django 4.2.8 on 2025-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0011_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
