# Generated by Django 4.2.8 on 2025-11-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XndApp", "0013_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="survey_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_cooking_equipment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_cooking_frequency",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_dietary_restrictions",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_favorite_recipe",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_ingredients",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_serving_size",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="survey_skill_level",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
