# Generated by Django 4.2.8 on 2025-11-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("XndApp", "0014_user_survey_completed_user_survey_cooking_equipment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="ingredients_embedding",
            field=models.JSONField(blank=True, help_text="재료 임베딩 벡터", null=True),
        ),
        migrations.AddField(
            model_name="recipes",
            name="name_embedding",
            field=models.JSONField(
                blank=True, help_text="레시피명 임베딩 벡터", null=True
            ),
        ),
    ]
