# Generated by Django 4.2.8 on 2025-11-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0016_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
