# Generated by Django 4.2.8 on 2025-11-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0017_purchase_completed_date_purchase_is_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shopping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
