# Generated by Django 4.2.8 on 2025-11-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XndApp', '0019_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeingredients',
            name='ingredient_pic',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='fridge_ingredients/'),
        ),
    ]
