// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5kqXT8PdsTOQuQjGnCue_SGQqQNHN2Zg',
    appId: '1:785144420139:web:46498b6431ba719f11d76e',
    messagingSenderId: '785144420139',
    projectId: 'example-84aab',
    authDomain: 'example-84aab.firebaseapp.com',
    storageBucket: 'example-84aab.firebasestorage.app',
    measurementId: 'G-ZBXFST2HC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLe16Xj_QQ4h1EFVaq4H849Ikmv-i89Sg',
    appId: '1:785144420139:android:b9917405cbd9fe1211d76e',
    messagingSenderId: '785144420139',
    projectId: 'example-84aab',
    storageBucket: 'example-84aab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81NpT37emVXnUWNkOxVkutH8HyCSkuB0',
    appId: '1:785144420139:ios:b36b22eaf33faf5711d76e',
    messagingSenderId: '785144420139',
    projectId: 'example-84aab',
    storageBucket: 'example-84aab.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81NpT37emVXnUWNkOxVkutH8HyCSkuB0',
    appId: '1:785144420139:ios:b36b22eaf33faf5711d76e',
    messagingSenderId: '785144420139',
    projectId: 'example-84aab',
    storageBucket: 'example-84aab.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5kqXT8PdsTOQuQjGnCue_SGQqQNHN2Zg',
    appId: '1:785144420139:web:1fbc176f1294593911d76e',
    messagingSenderId: '785144420139',
    projectId: 'example-84aab',
    authDomain: 'example-84aab.firebaseapp.com',
    storageBucket: 'example-84aab.firebasestorage.app',
    measurementId: 'G-PR5GBJ8M09',
  );
}
